/*
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
--exec dbo.sp_InsertF4111
Helpful Commands

DELETE FROM [JDE].[F4111]
      WHERE ilukid in (select ilukid from jde.F4111_Temp)

select count(*) from jde.f4111
select count(*) from jde.f4111_temp
-- =============================================
*/
CREATE PROCEDURE [dbo].[sp_InsertF4111]
	-- Add the parameters for the stored procedure here
	--<@Param1, sysname, @p1> <Datatype_For_Param1, , int> = <Default_Value_For_Param1, , 0>, 
	--<@Param2, sysname, @p2> <Datatype_For_Param2, , int> = <Default_Value_For_Param2, , 0>
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO [JDE].[F4111_Current]
           ([ILITM]
           ,[ILLITM]
           ,[ILAITM]
           ,[ILMCU]
           ,[ILLOCN]
           ,[ILLOTN]
           ,[ILPLOT]
           ,[ILSTUN]
           ,[ILLDSQ]
           ,[ILTRNO]
           ,[ILFRTO]
           ,[ILLMCX]
           ,[ILLOTS]
           ,[ILLOTP]
           ,[ILLOTG]
           ,[ILKIT]
           ,[ILMMCU]
           ,[ILDMCT]
           ,[ILDMCS]
           ,[ILCMOO]
           ,[ILKCO]
           ,[ILDOC]
           ,[ILDCT]
           ,[ILSFX]
           ,[ILJELN]
           ,[ILICU]
           ,[ILDGL]
           ,[ILGLPT]
           ,[ILDCTO]
           ,[ILDOCO]
           ,[ILKCOO]
           ,[ILLNID]
           ,[ILNLIN]
           ,[ILIPCD]
           ,[ILTRDJ]
           ,[ILTRUM]
           ,[ILAN8]
           ,[ILTREX]
           ,[ILTREF]
           ,[ILRCD]
           ,[ILTRQT]
           ,[ILUNCS]
           ,[ILPAID]
           ,[ILMCUZ]
           ,[ILOBJ]
           ,[ILSUB]
           ,[ILSBL]
           ,[ILSBLT]
           ,[ILAID]
           ,[ILASID]
           ,[ILCMMT]
           ,[ILPTSK]
           ,[ILVPEJ]
           ,[ILCTWT]
           ,[ILCWUM]
           ,[ILHDGJ]
           ,[ILRE]
           ,[ILSUMP]
           ,[ILTPRG]
           ,[ILFUF3]
           ,[ILFUF4]
           ,[ILFUF5]
           ,[ILFUF6]
           ,[ILMMEJ]
           ,[ILUPMJ]
           ,[ILTORG]
           ,[ILTDAY]
           ,[ILUSER]
           ,[ILPID]
           ,[ILCRDJ]
           ,[ILTERM]
           ,[ILUKID]
           ,[Date])
SELECT [ILITM]
      ,[ILLITM]
      ,[ILAITM]
      ,[ILMCU]
      ,[ILLOCN]
      ,[ILLOTN]
      ,[ILPLOT]
      ,[ILSTUN]
      ,[ILLDSQ]
      ,[ILTRNO]
      ,[ILFRTO]
      ,[ILLMCX]
      ,[ILLOTS]
      ,[ILLOTP]
      ,[ILLOTG]
      ,[ILKIT]
      ,[ILMMCU]
      ,[ILDMCT]
      ,[ILDMCS]
      ,[ILCMOO]
      ,[ILKCO]
      ,[ILDOC]
      ,[ILDCT]
      ,[ILSFX]
      ,[ILJELN]
      ,[ILICU]
      ,[ILDGL]
      ,[ILGLPT]
      ,[ILDCTO]
      ,[ILDOCO]
      ,[ILKCOO]
      ,[ILLNID]
      ,[ILNLIN]
      ,[ILIPCD]
      ,[ILTRDJ]
      ,[ILTRUM]
      ,[ILAN8]
      ,[ILTREX]
      ,[ILTREF]
      ,[ILRCD]
      ,[ILTRQT]
      ,[ILUNCS]
      ,[ILPAID]
      ,[ILMCUZ]
      ,[ILOBJ]
      ,[ILSUB]
      ,[ILSBL]
      ,[ILSBLT]
      ,[ILAID]
      ,[ILASID]
      ,[ILCMMT]
      ,[ILPTSK]
      ,[ILVPEJ]
      ,[ILCTWT]
      ,[ILCWUM]
      ,[ILHDGJ]
      ,[ILRE]
      ,[ILSUMP]
      ,[ILTPRG]
      ,[ILFUF3]
      ,[ILFUF4]
      ,[ILFUF5]
      ,[ILFUF6]
      ,[ILMMEJ]
      ,[ILUPMJ]
      ,[ILTORG]
      ,[ILTDAY]
      ,[ILUSER]
      ,[ILPID]
      ,[ILCRDJ]
      ,[ILTERM]
      ,[ILUKID]
      ,[Date]
  FROM [JDE].[F4111_Temp] Live
  Where --(dateadd(yy,[GLUPMJ]/1000,0) + [GLUPMJ]%1000 - 1) > dateadd(dd,-5,getdate()) And 
  not exists (select 1 FROM [PTODS].[JDE].[F4111_Current] ODS
								where ods.ILUKID = Live.ILUKID)	

END